## ARRAY

An Array is a Data Structure which contains elements / data of a particular data type alone. This is the key difference with respect to List.

In [18]:
a = [1, 2, 4, 5, 6, 7]

In [3]:
import numpy as np

In [36]:
b = np.array(a)
print(type(b))
print(b)

arr = b.copy()

<class 'numpy.ndarray'>
[1 2 4 5 6 7]


In [9]:
a1 = [1, 2, 4, 5, 6, 'mango']

In [11]:

b1 = np.array(a1)
print(b1)

## All the integers are converted to strings, because of the prescence of a string datatype in the list a1.

['1' '2' '4' '5' '6' 'mango']


## SHAPE

Shape is the indication of the number of rows and columns that exists in the array.
--> Shape is an attribute of the array object

In [14]:
b1.shape

(6,)

In [20]:
b.reshape(3,2)

# The number of elements must be the same for shaping and reshaping

array([[1, 2],
       [4, 5],
       [6, 7]])

## ARANGE, LINSPACE

arange is the method of numpy class for creating a range of numbers [start, end).

linspace is the method of numpy class for creating a sequence of 'num' numbers equally spaced between [start, end]

In [35]:
arangeArr = np.arange(10)
print(arangeArr)

linspaceArr = np.linspace(0,10, num=10)
print(linspaceArr)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [34]:
# Copying and Broadcasting

arangeArr_copy = arangeArr[:]
arangeArr_copy  
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


arangeArr_copy[4:] = 100
arangeArr_copy

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100])

## CONDITIONS

Any Condition directed at the array will be implicitly applied to each of the element constituting to it.

In [37]:
arr

array([1, 2, 4, 5, 6, 7])

In [38]:
b = 3
arr > 3


array([False, False,  True,  True,  True,  True])

In [39]:
arr[arr>3]

array([4, 5, 6, 7])

## RANDOM

This is a subclass of numpy module

In [44]:
np.random.rand(6,1)

#creates elements of standard distribution based on the given shape.

array([[0.82444639],
       [0.60960266],
       [0.56436726],
       [0.25226742],
       [0.62431987],
       [0.18988918]])

In [47]:
np.random.randn(6,1)

#creates elements of standard normal distribution based on the given shape.

array([[ 0.48359433],
       [ 0.6757642 ],
       [ 1.24932796],
       [-1.3593205 ],
       [ 0.33897363],
       [ 1.63077421]])

In [53]:
np.random.randint(0,10, size = (10,10))

#creates random integers between the given start and end integers of the given size

array([[2, 2, 3, 7, 7, 0, 7, 6, 0, 5],
       [0, 3, 0, 6, 6, 0, 6, 3, 0, 3],
       [0, 6, 2, 3, 4, 6, 3, 9, 4, 9],
       [7, 1, 0, 8, 4, 9, 8, 1, 4, 4],
       [9, 1, 4, 0, 5, 9, 0, 7, 8, 6],
       [7, 9, 5, 6, 3, 2, 4, 1, 7, 5],
       [1, 9, 9, 2, 7, 9, 6, 7, 8, 6],
       [2, 0, 7, 7, 0, 0, 2, 8, 1, 1],
       [3, 7, 7, 2, 4, 8, 2, 7, 6, 0],
       [3, 3, 6, 6, 2, 2, 3, 0, 4, 6]])